version: 2
jobs:
  build:
    docker:
      - image: debian:buster
        environment:
          CXX: /usr/bin/g++
          CC: /usr/bin/gcc
          CONAN_CPU_COUNT: 4
    steps:
      - run: apt-get update
      - run: apt-get install -y git
      - run:
          name: Avoid hosts unknown for github
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Cloning repo
          command: git clone --recursive https://github.com/MinterTeam/mhwallet .
      - restore_cache:
          keys:
            - custom-pkgs-{{ checksum ".circleci/setup.sh" }}
      - run:
          name: Preparing
          command: $(which bash) .circleci/setup.sh
      - save_cache:
          key: custom-pkgs-{{ checksum ".circleci/setup.sh" }}
          paths:
            - /tmp/pkgs
      - run: pip3 install setuptools -U
      - run: pip3 install conan
      - run: conan remote add edwardstock https://api.bintray.com/conan/edwardstock/conan-public
      - run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - run: conan remote add minter https://api.bintray.com/conan/minterteam/minter
      - run: conan user -p $BINTRAY_API_KEY -r minter edwardstock
      - run: mkdir -p _build
      - restore_cache:
          keys:
            - conan-dir-{{ checksum "conanfile.py" }}
      - run:
          name: Configuring
          command: conan remove --locks && cd _build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DMINTER_TX_TEST=ON
      - save_cache:
          key: conan-dir-{{ checksum "conanfile.py" }}
          paths:
            - /root/.conan
      - run:
          name: Testing
          command: $(which bash) .circleci/test.sh
      - run:
          name: "Deploy to Conan"
          command: $(which bash) .circleci/deploy.sh